### ISSUE TITLE
Get rid of the horizontal belt

### ISSUE THREAD

**Issue by DomML** [Pierro55/Loop#3]
Hello.
First off, it's a very nice project, and I seriously consider to replicate it.
I was wondering if I would be possible to remove the horizontal axis at the top to only keep the vertical one (on the side), where the part interacting with the extruder would be located.
I believe this would simplify the design, but there may be a reason you didn't did it like that?
Still, great project,
DML.

**Comment by Pierro55** [comment]
This would probably make the design more complex as you have to avoid the X-axis part on the left and you would probably lose even more Z-height because you have to move the extruder down to move the ejector arm. The ejector arm would also collide with the extruder. You would have to place the arm and the mechanism at the back of the printer which might lead to not being able to push prints all the way off the buildplate.

These are the thing that come spontaneously to my mind but feel free to remix the system. You can find the STEP files in the 3D files folder.

**Comment by DomML** [comment]
Nice thanks!
