### ISSUE TITLE
Bed mechanics cover blocks movement

### ISSUE THREAD

**Issue by Kertonix** [Pierro55/Loop#5]
Bed mechanics cover blocks movement of the bed towards front. 
Because of it belt test cannot be completed.

**Comment by Pierro55** [comment]
Hey Kertonix,
can you please post a picture of how you mounted the cover?

**Comment by Pierro55** [comment]
> Hey Kertonix,
> can you please post a picture of how you mounted the cover?

**Comment by Kertonix** [comment]
![20221205_085023](https://user-images.githubusercontent.com/47567151/205583075-bf443d8a-171a-493e-841f-1ec16a59e587.jpg)
![20221205_085035](https://user-images.githubusercontent.com/47567151/205583093-bc6d8e5f-8f01-4f74-bc9a-902acaec08be.jpg)

**Comment by Pierro55** [comment]
@Kertonix Thanks
I've just run the belt test (Prusa setting) on my machine and it worked just fine.
Checked the CAD model as well and nothing is colliding anywhere:
![cap_1](https://user-images.githubusercontent.com/57869093/205708757-1a2ae770-274a-4e8a-98a9-f04eec0c7abb.PNG)

![cap_2](https://user-images.githubusercontent.com/57869093/205708816-0475afad-aa89-4be4-a04a-55eb1f6244c6.PNG)

But what I've noticed on your setup, you have the old version of the Y-rod holder. Do you have a MK3S instead of a MK3S+?
Maybe they've changed the belt tensioner for the Y-axis as well.

If that does not solve the problem, could you please post a video of the problem (maybe put the printer on its side and film the underside of the y bed while it is moving)?

**Comment by Kertonix** [comment]
Cutting thickening of "Bed mechanics cover MIRROR" lip did the job. 
![20221206_085045](https://user-images.githubusercontent.com/47567151/207017080-af1e1349-486e-4496-85a6-9d92a10b343a.jpg)
![20221206_085040](https://user-images.githubusercontent.com/47567151/207017084-48c7ffc0-2ca8-4398-b59d-ab69f15938b4.jpg)
![20221206_081626](https://user-images.githubusercontent.com/47567151/207017090-3eb1d08a-daac-4fab-8445-ca8826b80dc5.jpg)
![20221206_083437](https://user-images.githubusercontent.com/47567151/207017094-a4069694-5bb2-4bab-bf9a-955ece95da51.jpg)

**Comment by Kertonix** [comment]
It came from cutting (with knife and hot-air)
